ReadMe/Onboarding Review
codeforpdx/PASS pull request #18
Opened 2023-01-26 01:09 UTC by danicaboe

Still working on it, so definitely some gaps that look a little wonky. Please let me know thoughts, improvements, things to remove/add.

2023-01-26 03:07 UTC, k-mack requested changes
This is looking good, and it will be a good basis going forward. I made several comments.

2023-01-26 03:07 UTC, k-mack commented on README.md
> +## If you're new to the team, check out our [onboarding](https://github.com/codeforpdx/PASS/blob/db/onboarding/onboarding.md) file.
I believe GitHub allows links to files in Markdown to be relative paths. E.g., `[onboarding](onboarding.md)`. This will allow your branch to be deleted after the merge and the link will still work.

2023-01-26 03:07 UTC, k-mack commented on README.md
> +### Inrupt JavaSctipt Client Libraries
I think a little blurb about Inrupt leading the way for developing with Solid and providing the link to Inrupt's documentation would suffice. (https://docs.inrupt.com/developer-tools/javascript/client-libraries/)

2023-01-26 03:07 UTC, k-mack commented on README.md
> +### RDF
Consider adding:
* RDF Primer (https://www.w3.org/TR/rdf11-primer/)
* Turtle spec (https://www.w3.org/TR/turtle/)

2023-01-26 03:07 UTC, k-mack commented on README.md
> +### Document Hashing
We might want to remove this for now until we have a better handle on it ourselves.

2023-01-26 03:07 UTC, k-mack commented on README.md
> +| Colton              | Andy                  | Kyle       | Danica                  |
I think Colton has stepped back for now.

2023-01-26 19:16 UTC, danicaboe commented on README.md
> +## If you're new to the team, check out our [onboarding](https://github.com/codeforpdx/PASS/blob/db/onboarding/onboarding.md) file.
Updated, didn't know that, thanks for pointing it out.

2023-01-26 19:17 UTC, danicaboe commented on README.md
> +### Inrupt JavaSctipt Client Libraries
I added it, lmk if you think I should elaborate further.

2023-01-26 19:18 UTC, danicaboe commented on README.md
> +### RDF
Added. Let me know if I should simplify. Or if I'm not explaining our uses of the two within PASS properly.

2023-01-26 19:18 UTC, danicaboe commented on README.md
> +### Document Hashing
Removed!

2023-01-26 19:21 UTC, danicaboe commented on README.md
> +| Colton              | Andy                  | Kyle       | Danica                  |
Should we maybe just keep you, Jared, Gabby, Kyle, Flo, me, Wilf and Katherine listed? Maybe add people after they've been on the project for a certain amount of time? Or have people add themselves as a task when they are first onboarding?

2023-02-01 03:20 UTC, leekahung commented
Hey everyone, it's Ka Hung! Just want to make a comment here, so I could get started!

2023-02-01 04:08 UTC, k-mack commented on README.md
> +| Colton              | Andy                  | Kyle       | Danica                  |
> Should we maybe just keep you, Jared, Gabby, Kyle, Flo, me, Wilf and Katherine listed?

That sounds good to me!

2023-02-01 04:11 UTC, k-mack commented on README.md
> +### RDF
LGTM

2023-02-02 16:54 UTC, Jared-Krajewski reviewed
good write up!

2023-02-02 16:54 UTC, Jared-Krajewski commented on onboarding.md
> +
Link to the POC demo in addition might be useful as well since it has functionality built in vs just a blank template for other to experiment.  https://github.com/codeforpdx/PASS/tree/jk/solidTests

2023-02-08 03:53 UTC, k-mack approved these changes

2023-02-08 03:57 UTC, Jared-Krajewski commented
merged after 2/7 meeting.

2023-02-08 03:57 UTC, merged