Fixing redundant code from issue 218
codeforpdx/PASS pull request #276
Opened 2023-06-24 01:45 UTC by andycwilliams

Quick merge to fix my error in removing redundant code. With issue #218, `AddClient.jsx` was refactored into `AddClientModal.jsx` and therefore no longer needed. It was to be deleted but I didn't before going ahead with the merge. This fixes the issue.

2023-06-24 04:11 UTC, leekahung commented
While I saw that the earlier PR has been approved, please refrain from merging unless you're sure things have been double-checked on your end.

2023-06-24 04:43 UTC, xscottxbrownx approved these changes
Looks good to me.  Just deleting the original `AddClient.jsx` and fixing it's index.js file to match

2023-06-25 15:20 UTC, leekahung commented on src/components/Clients/AddClientModal.jsx
For the Modal, since we're already using MUI components instead of `<input>`, could we swap out the useField hooks for givenName and familyName with useStates?

Think we could also remove the disable eslint lines here without eslint complaining.

2023-06-25 15:21 UTC, leekahung requested changes
See feedback for requested changes

2023-06-28 22:15 UTC, leekahung commented on src/components/Clients/AddClientModal.jsx
Any progress in this front? Think it'll be a good update to have while we're having this patched up.

2023-06-29 01:52 UTC, andycwilliams commented on src/components/Clients/AddClientModal.jsx
Been extremely busy with work. Will try to get back in the PASS rhythm now.

2023-06-29 02:45 UTC, leekahung commented on src/components/Clients/AddClientModal.jsx
No rush.

2023-06-30 20:23 UTC, leekahung approved these changes
I think this should be fine for merging.

2023-06-30 22:18 UTC, merged