Clean-up Profile Components
codeforpdx/PASS pull request #401
Opened 2023-09-05 08:51 UTC by leekahung

## Clean-up Profile Components

The overall aim of this PR is simply to go through the existing codebase and cleaning up the existing component files. This one specifically will target the components in `src/components/Profile`. I aim to subsequently update the other component files in their own PRs.

---
## This PR:
**1.**    Cleans up codebase in `src/components/Profile`
**2.**   Cleans up typedef in `src/typedefs.js`

---
## The files this PR effects:

### Components
- `src/components/Profile/ProfileComponent.jsx`
- `src/components/Profile/ProfileEditButtonGroup.jsx`
- `src/components/Profile/ProfileImageField.jsx`
- `src/components/Profile/ProfileImageField.jsx`

### Other Files
- `src/typedefs.js`

---
## Future Steps/PRs Needed to Finish This Work (optional):
- Additional steps include cleaning up other files within `src/components/`

2023-09-05 14:52 UTC, xscottxbrownx requested changes

2023-09-05 14:52 UTC, xscottxbrownx commented on src/components/Profile/ProfileComponent.jsx
> -                    name="date"
replace one of these deleted attributes with `disableFuture` : https://mui.com/x/api/date-pickers/date-picker/

2023-09-05 14:52 UTC, xscottxbrownx commented on src/components/Profile/ProfileComponent.jsx
> -            disabled={contactProfile}
do we want to be able to edit a `contact`'s profile info?  
Or do you feel these are unnecessary due to the `EDIT` button being conditionally rendered?

The `EDIT` button still rendered when I clicked on a contact's profile link from the contact table.
It shows their webID at top, but all my info below (don't remember if we already discussed this or had issue for it.)

2023-09-05 14:52 UTC, xscottxbrownx commented on src/components/Profile/ProfileComponent.jsx
> -                    name="date"
Right now you can choose future dates in DOB field.

2023-09-05 17:50 UTC, leekahung commented on src/components/Profile/ProfileComponent.jsx
> -                    name="date"
Got `disableFuture` included.

2023-09-05 17:53 UTC, leekahung commented on src/components/Profile/ProfileComponent.jsx
> -            disabled={contactProfile}
Yeah, I think we've discussed this before. It's related to the bug mentioned in Issue #386 that still needs to be patched up. I believe the video example shown there is something that you've encountered here.

2023-09-05 18:37 UTC, leekahung commented on src/components/Profile/ProfileComponent.jsx
> -            disabled={contactProfile}
Created a new PR to patch up this issue for good, see PR #402.

2023-09-06 00:07 UTC, xscottxbrownx approved these changes

2023-09-08 22:33 UTC, merged