Issue 393 footer enhancement
codeforpdx/PASS pull request #404
Opened 2023-09-09 06:46 UTC by Raspber

---
name: Pull Request
about: Create a pull request to merge your code into the PASS codebase
title: 'Enhance: app footer'
labels: 'enhancement, footer'
assignees: 'Raspber'

---

Enhance App Footer

---
## This PR:
**1.**    Updated "proposal" button to a call to action in the RenderCallToActionSection.jsx
**2.**    Updated Twitter icon to the newest X icon. 
**3.**    Removed unnecessary items within the RenderCompanyInfoSection.jsx, such as the codepdx logo with the tagline, and the built by. 

---
## The files this PR effects:

### Components

- Footer.jsx
- RenderCallToActionSection.jsx
- RenderCompanyInfoSection.jsx

### Tests
No test files are affected

### Other Files
No other files are affected

---
## Screenshots (if applicable):
![footer-no-update](https://github.com/codeforpdx/PASS/assets/20136800/9936f001-6efa-455b-84cc-71647d23ea21)
![footer-updated](https://github.com/codeforpdx/PASS/assets/20136800/fecc2a1f-44a7-4098-8f51-7f75b08f0ccd)

---
## Additional Context (optional):
Will be creating a new issue to create new pages/routes for the terms and conditions link. 

---
## Future Steps/PRs Needed to Finish This Work (optional):

---
## Issues needing discussion/feedback (optional):

2023-09-10 07:39 UTC, leekahung requested changes
See comment

2023-09-10 07:39 UTC, leekahung commented on src/components/Footer/RenderCompanyInfoSection.jsx
> +const TwitterIcon = (props) => (
If this is simply a new custom component for the new Twitter Icon, I don't think we need to add a prop to this.

2023-09-10 07:39 UTC, leekahung commented on src/components/Footer/RenderCompanyInfoSection.jsx
> +  <SvgIcon {...props} viewBox="0 0 512 512" style={{ width: '1.25em', height: '1.25em' }}>
With regards to the attributes, think we could use `sx` instead of `style` for MUI.

2023-09-10 08:36 UTC, Raspber commented
> See comment

Will get this sorted 👍🏽

2023-09-11 09:07 UTC, leekahung approved these changes
Think this is good to go for merger. Given that it's fairly small, I think we could get this merged into Master as well along with PR #397 in the version update.

2023-09-11 16:22 UTC, xscottxbrownx requested changes
Overall good changes.
---
1) There's an issue with the icon spacing if you resize browser.
2) I would say go ahead and change the other footer file as well to make the copyright `CODE PDX` (dropping the "for" as we are rebranding, and all caps.)

2023-09-11 16:22 UTC, xscottxbrownx commented on src/components/Footer/RenderCompanyInfoSection.jsx
> +      <Typography color="tertiary.main" variant="h5" mb={1}>
Now the icons aren't as responsive and have issues at certain screen sizes.

<img width="613" alt="Screenshot 2023-09-11 at 9 11 00 AM" src="https://github.com/codeforpdx/PASS/assets/71395931/40ac419a-63bb-4c47-ba21-28e2865a7c8b">

2023-09-11 16:22 UTC, xscottxbrownx commented on src/components/Footer/RenderCallToActionSection.jsx
> +      target="_blank"
not sure if I'm wrong from a security standpoint, but you don't need line 33 or 34 with a `mailto`, it opens in the email client not browser.

2023-09-11 17:45 UTC, Raspber commented
> Overall good changes.
> ---
> 1) There's an issue with the icon spacing if you resize browser.
> 2) I would say go ahead and change the other footer file as well to make the copyright `CODE PDX` (dropping the "for" as we are rebranding, and all caps.)

Will get this sorted out today.

2023-09-13 04:50 UTC, leekahung commented
Hey @Raspber. What is the progress of this? I see that Scott pointed out some thing that needs to be addressed.

2023-09-13 05:00 UTC, Raspber commented
> Hey @Raspber. What is the progress of this? I see that Scott pointed out some thing that needs to be addressed.

Working on this as well

2023-09-14 02:46 UTC, andycwilliams commented
Since we're transitioning the organization name from Code for PDX to CODE PDX, we'll eventually need to update this again with the new branding. However, for this PR I think it's fine as is since we're not entirely sure when that whole process will be complete.

2023-09-19 05:34 UTC, Raspber commented
ah sorry, i reguested review but i have yet to make the correct changes. please ignore.

2023-09-19 18:41 UTC, xscottxbrownx approved these changes

2023-09-21 16:38 UTC, ogorman89 commented
Nice 👍 

Like @xscottxbrownx said, the social icons get pretty crowded right before the breakpoint for mobile (just over ~600px viewport). I recommend we merge as is. 

There will be more work on the footer with the forthcoming updates from the UI team.

2023-09-21 16:40 UTC, ogorman89 approved these changes
Per conversation at the work session. This looks good to me to merge as is.

2023-09-21 18:33 UTC, merged