improve react query behavior
codeforpdx/PASS pull request #459
Opened 2023-10-16 05:05 UTC by timbot1789

A small improvement to react query behavior. React query automatically refetches any data marked as "stale" when it's requested. By default `staleTime` is set to zero, everything is automatically stale and always refetched. This change sets `staleTime` to one minute. Documents won't be refetched until they're a minute old. This should reduce some redundant fetches.

2023-10-16 12:40 UTC, xscottxbrownx commented
sounds good to me.

not sure if leaving a space between the jsdoc typedef and the additions is needed or not - so as to not link the jsdoc with the additions to codebase?

2023-10-16 16:59 UTC, leekahung commented
> sounds good to me.
> 
> not sure if leaving a space between the jsdoc typedef and the additions is needed or not - so as to not link the jsdoc with the additions to codebase?

If they're imported typedefs, they don't to be directly above the lines of code it's being used for like what we do for components which JSDoc needs to be directly above them to be associated.

2023-10-16 17:02 UTC, leekahung requested changes
I've just noticed that the two imported typedefs aren't being used in `App.jsx` at all. They're likely remnants from an earlier time in the project, but I think we could actually remove them here since they're not longer in use.

2023-10-21 19:24 UTC, timbot1789 commented
Fixed JSDoc typedefs. @leekahung can you add a work item for yourself to add jsdoc validation into the project as part of the linter? Checking this stuff manually is pretty inefficient.

2023-10-21 19:56 UTC, leekahung commented
> Fixed JSDoc typedefs. @leekahung can you add a work item for yourself to add jsdoc validation into the project as part of the linter? Checking this stuff manually is pretty inefficient.

The plugin for the linter for JSDoc is already in the project. I'll see if I could get the specific validation call turned on for it for imports like this.

2023-10-21 19:57 UTC, leekahung approved these changes
Looks good for merging.

2023-10-21 19:59 UTC, merged