#39 - Adds Base Configuration Changes for ESLint
codeforpdx/PASS pull request #46
Opened 2023-03-09 03:40 UTC by GoodGuyGregory

@leekahung This expands on what we discussed in the meeting this week. 

It should add base configurations. I recommend we go line by line with this one locally, if all of your changes are up to date in Development, 

I should have some time Friday if you're available on Discord

2023-03-09 10:04 UTC, leekahung requested changes
These feedback will likely be discussed on our Friday discussion. Don't see much of a problem with lint rules being presented here. It's very similar to what I've been exploring. Just need to hash things out by line as mentioned on Discord on what rules to add or drop.

2023-03-09 10:04 UTC, leekahung commented on .prettierignore
> +./src/index.html
I don't think Line 3 is necessary. The base index.html is located on the root directory: ./

2023-03-09 10:04 UTC, leekahung commented on src/App.jsx
> +const AppHeader = () => {return (
Can review arrow function block statements for React in Friday's discussion, but essentially, components can be made without explicit returns if it's only return JSX Elements: https://stackoverflow.com/questions/53203257/making-components-with-curly-brackets-versus-parenthesis-when-using-functional-c

There's an example of what's shown in StackOverflow in Development's updated AppHeader without the explicit return.

2023-03-09 10:04 UTC, leekahung commented on src/components/Form/CrossPodWrite.jsx
> +import { useState, React } from 'react';
Should be: import React, { useState } from 'react';

2023-03-09 10:04 UTC, leekahung commented on src/components/Form/DocumentSelection.jsx
> +				return <option key={index}>{doc}</option>;
Found a workaround for key prop. Decided to just use the first word of multiworded docType, which can be obtained using: doc.split(' ')[0]. Can be discussed on Friday.

Check out Development's DocumentSelection.jsx for the workaround.

2023-03-11 01:14 UTC, GoodGuyGregory commented on .prettierignore
> +./src/index.html
removing now

2023-03-11 01:46 UTC, closed without merging