Add max height for autocomplete and signInModal components
codeforpdx/PASS pull request #541
Opened 2023-11-25 08:43 UTC by rioredwards

## This PR:
Resolves #539

## Screenshots (if applicable):

https://github.com/codeforpdx/PASS/assets/55720928/713f6846-be49-4fb2-a6df-447355ce373f

## Additional Context (optional):
The issue this PR resolves is actually asking to add vertical scrolling functionality to the Autocomplete. However, adding a max height to the component addresses the issue... The Autocomplete component had scrollable functionality all along, so by limiting its height, this allows the component's content to be scrollable.

2023-11-25 11:31 UTC, leekahung commented
As stated from Issue #539:

> Still think it'll be better if we could keep the modal from changing and allow the autocomplete vertical scroll

Is it possible to just have the <Autocomplete> drop down without the modal changing?

2023-11-25 18:47 UTC, timbot1789 approved these changes

2023-11-25 21:34 UTC, leekahung requested changes
See earlier comment about modal.

2023-11-27 09:18 UTC, rioredwards commented
> Is it possible to just have the drop down without the modal changing?

I think this must be possible, but I couldn't figure out how to do it...

I tried just limiting the height of the Autocomplete component, but the parent component was still resizing as if the Autocomplete's height wasn't being limited... From what I could find, MUI doesn't provide an intuitive way to limit the height of this component, so this was the best I could come up with. 

I'm still getting the hang of MUI, but if anyone here wants to dig in and find a better solution, I would be happy to see it done right!

2023-11-27 12:51 UTC, leekahung commented
> I think this must be possible, but I couldn't figure out how to do it...
> 
> I tried just limiting the height of the Autocomplete component, but the parent component was still resizing as if the Autocomplete's height wasn't being limited... From what I could find, MUI doesn't provide an intuitive way to limit the height of this component, so this was the best I could come up with.
> 
> I'm still getting the hang of MUI, but if anyone here wants to dig in and find a better solution, I would be happy to see it done right!

No worries @rioredwards , all good! Had poked around a bit locally too without much luck. Think we could just approve this for now as a tentative solution.

2023-11-27 12:51 UTC, leekahung approved these changes

2023-11-27 19:55 UTC, merged