571/edit contacts
codeforpdx/PASS pull request #659
Opened 2024-07-03 18:41 UTC by JaeGif

## This PR:
Resolves #571 

Can now edit contacts clicking the icon, and changing just their given or last names. OIDC and Username are inferred from the PodUrl.

- Adds editing state to AddContactModal 
- Selectively displays oidc and username inputs if editing
- Added parsePodUrl helper function to extract the oidc and the username from the existing podurl when editing a contact

Extension of the work done at #613 

Future work:
parsePodUrl can probably be improved if the need arises, the function right now assumes all oidc's will be standard url's which I hope is the case.

2024-07-03 18:47 UTC, JaeGif commented
Failing tests don't seem to be related to this PR.

2024-07-03 19:59 UTC, leekahung commented
> Failing tests don't seem to be related to this PR.

Yeah, the tests are from an earlier PR that needs to be fixed.

2024-07-03 20:07 UTC, leekahung commented on src/components/Contacts/ContactListTable.jsx
> +  const [contacts_, setContacts] = useState(contacts);
Think we could use `contactsList` as the state being set instead of `contacts_` and `contacts` as the incoming state.

2024-07-03 20:16 UTC, leekahung approved these changes
Non-blocking comment on the name of the state used for `contacts_`. It's not being used anywhere else, but for `useEffect` but think it'll be better to use `contactsList`.

2024-07-03 20:36 UTC, andycwilliams requested changes
I'm unable to edit the contact as the Edit Contact button stays disabled. Requesting changes as a safety measure to ensure it does indeed function as intended.

The issue says the web ID should be editable as well, though that is trickier.

2024-07-03 20:53 UTC, JaeGif commented
> I'm unable to edit the contact as the Edit Contact button stays disabled. Requesting changes as a safety measure to ensure it does indeed function as intended.
> 
> 
> 
> The issue says the web ID should be editable as well, though that is trickier.

What does the test user you're using look like? Are you using a different provider than localhost potentially?

2024-07-03 21:05 UTC, andycwilliams commented
@JaeGif I'm using solidcommunity for both the account I'm logged in with as well as the contacts I try to edit

2024-07-03 21:16 UTC, JaeGif commented
> @JaeGif I'm using solidcommunity for both the account I'm logged in with as well as the contacts I try to edit

I see. It looks like the different provider formats the podURL differently. I found the schema for the different podURL possibilities and will update the parsing function.

2024-07-03 21:28 UTC, leekahung commented
> > @JaeGif I'm using solidcommunity for both the account I'm logged in with as well as the contacts I try to edit
> 
> I see. It looks like the different provider formats the podURL differently. I found the schema for the different podURL possibilities and will update the parsing function.

Yeah, the format for webIds on solidcommunity.net uses a `https://<username>.<provider>/` instead of the usual `https://<provider>/<username>/` format from community solid server

2024-07-03 21:42 UTC, JaeGif commented
> > I'm unable to edit the contact as the Edit Contact button stays disabled. Requesting changes as a safety measure to ensure it does indeed function as intended.
> > The issue says the web ID should be editable as well, though that is trickier.
> 
> What does the test user you're using look like? Are you using a different provider than localhost potentially?

I believe I've fixed the issue you had. 

As for the WebID, I'm not convinced that it's something that should be "editable" as my understanding is that it's a unique identifier of a user. 

If we are sure we do want this though, I believe I can add this functionality quickly.

2024-07-03 21:53 UTC, andycwilliams commented
@JaeGif Will take another look soon. Have you tested other pod providers, like opencommons?

The issue states to be able to edit the Web Id too. If we don't think parts of an issue are important, it would be best to mention that and open for discussion beforehand.

2024-07-03 22:25 UTC, leekahung commented
> The issue states to be able to edit the Web Id too. If we don't think parts of an issue are important, it would be best to mention that and open for discussion beforehand.

There's additional context to that issue. As stated since webIds is the identifier for the object, updating webId would likely require deleting the old entry and adding a new one anyways. The solution here is fine.

If users want to, they could simply make a new contact with the new webId. It's like adding a person's gmail account and their yahoo account onto contacts.

2024-07-03 22:36 UTC, andycwilliams commented
It can just be mentioned in the PR that some part intentionally wasn't added because you don't think it's actually needed. It's good to have more communication and ensure that nothing appears to be an oversight or anything.

2024-07-16 23:41 UTC, leekahung commented
Hey @JaeGif @andycwilliams, would like to check up with you guys. What's the current status of this PR?

2024-07-17 00:20 UTC, andycwilliams commented
> Hey @JaeGif @andycwilliams, would like to check up with you guys. What's the current status of this PR?

Once it's possible to update the contact regardless of OIDC Provider I'm ready to approve

2024-07-17 16:46 UTC, JaeGif commented
> > Hey @JaeGif @andycwilliams, would like to check up with you guys. What's the current status of this PR?
> 
> Once it's possible to update the contact regardless of OIDC Provider I'm ready to approve



> > Hey @JaeGif @andycwilliams, would like to check up with you guys. What's the current status of this PR?
> 
> Once it's possible to update the contact regardless of OIDC Provider I'm ready to approve

I've checked with all the current oidc providers, and parsePodUrl successfully parsed all providers on the VITE_OIDC_WEBIDS list. 

I'm not particularly good at tests so I'm uncertain how to best write a unit test for this as the parsePodUrl function is inside of the AddContactModal. Everything I can think of needs a separate test for each OIDC which doesn't feel like the best way to do it.  

I've tested the function by separating parsePodUrl to it's own file locally, and iterating across VITE_OIDC_WEBIDS. All oidc's and usernames are parsed out correctly in this way.

2024-07-17 19:04 UTC, andycwilliams commented
> I've checked with all the current oidc providers, and parsePodUrl successfully parsed all providers on the VITE_OIDC_WEBIDS list.
> 
> I'm not particularly good at tests so I'm uncertain how to best write a unit test for this as the parsePodUrl function is inside of the AddContactModal. Everything I can think of needs a separate test for each OIDC which doesn't feel like the best way to do it.
> 
> I've tested the function by separating parsePodUrl to it's own file locally, and iterating across VITE_OIDC_WEBIDS. All oidc's and usernames are parsed out correctly in this way.

If it works for all providers then this is pretty much ready. The only remaining thing is that the development branch has since gotten new merges, so this will need updating. Shouldn't be too much though, just adding the same functionality as a menu item for the mobile version of the contacts table.

As for tests, yes normally we want them completed with each PR. However, I'm making an exception for MVP by creating an issue (#662) to address all failing tests. So if you can write them, or just as much as you can, then that's great, but otherwise it ought to be covered by that.

2024-07-18 17:18 UTC, JaeGif commented
> > I've checked with all the current oidc providers, and parsePodUrl successfully parsed all providers on the VITE_OIDC_WEBIDS list.
> > I'm not particularly good at tests so I'm uncertain how to best write a unit test for this as the parsePodUrl function is inside of the AddContactModal. Everything I can think of needs a separate test for each OIDC which doesn't feel like the best way to do it.
> > I've tested the function by separating parsePodUrl to it's own file locally, and iterating across VITE_OIDC_WEBIDS. All oidc's and usernames are parsed out correctly in this way.
> 
> If it works for all providers then this is pretty much ready. The only remaining thing is that the development branch has since gotten new merges, so this will need updating. Shouldn't be too much though, just adding the same functionality as a menu item for the mobile version of the contacts table.
> 
> As for tests, yes normally we want them completed with each PR. However, I'm making an exception for MVP by creating an issue (#662) to address all failing tests. So if you can write them, or just as much as you can, then that's great, but otherwise it ought to be covered by that.

Sounds good. Just reconciled the branches. Some slight changes had to be made to fit the new layout, made the minor changes and tested in every way I can think of and got it working.

2024-07-18 20:13 UTC, andycwilliams approved these changes
Can't test every OIDC provider to ensure they're all editable but if you tested them that's great

I'm approving although there are a couple of very minor changes I'd like. But they don't change functionality

2024-07-18 20:13 UTC, andycwilliams commented on src/components/Modals/AddContactModal.jsx
> + * @param {Function} props.setShowAddContactModal - Toggle modal
Duplicate line

2024-07-18 20:13 UTC, andycwilliams commented on src/components/Contacts/ContactListTable.jsx
> +
Empty line can be removed

2024-07-18 20:13 UTC, andycwilliams commented on src/components/Contacts/ContactListTableMobile.jsx
> +
Empty line. Also could move up EditIconOutlined to keep alphabetized.

2024-07-18 20:37 UTC, JaeGif commented on src/components/Contacts/ContactListTableMobile.jsx
> +
Made the minor changes, if it's alright with you I'll go ahead and merge

2024-07-18 20:46 UTC, andycwilliams commented on src/components/Contacts/ContactListTableMobile.jsx
> +
Go ahead. Great work!

2024-07-18 20:47 UTC, merged