Material UI
codeforpdx/PASS pull request #75
Opened 2023-04-04 21:57 UTC by andycwilliams

2023-04-05 06:51 UTC, leekahung requested changes
Minor review for now, will go more in-depth once #74 is merged to Development.

2023-04-05 06:51 UTC, leekahung commented on .parcel-cache/092db1189cc128d8
.parcel-cache and dist directories can be removed from pull request.

For Parcel, we're no longer using it as our bundler. For dist, the directory will be built for deployment in our production build.

2023-04-05 06:51 UTC, leekahung commented on src/components/Login/Login.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
In Line 1, PR #74 will deal with linting rule by moving this into eslintrc.js, so the can be removed for now (see .eslintrc.js from branch issue-72/user-list-management if you wish to implement that rule to your branch)

2023-04-06 04:49 UTC, andycwilliams commented on .parcel-cache/092db1189cc128d8
These have been removed in the lastest commit

2023-05-09 04:40 UTC, Jared-Krajewski commented
closing pull request due to new approach being used to implement MUI.

2023-05-09 04:40 UTC, closed without merging